# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ uat ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: export variables
        run: sh script.sh
        
      - name: print env
        run: cat $GITHUB_ENV
      
      # Runs a single command using the runners shell
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
      
      - name: print
        run: echo "${{ env.runid }}"
        
      - name: ssh proxy command
        uses: appleboy/ssh-action@master
        env:
          RID: ${{ env.runid }}
          PT: ${{ env.port }}
        with:
          host: 172.0.1.81
          username: opc
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          proxy_host: 193.122.68.49
          proxy_username: opc
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_port: 22
          envs: RID,PT
          script: |
            echo "sudo -E /usr/local/bin/mlflow sagemaker run-local -m runs:/$RID/model -i my-container -p $PT"
